import SignInCard from "~/components/SignInCard";
import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";
import { useEffect } from "react";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();
  const router = useRouter();

  useEffect(() => {
    if (sessionData?.user) {
      void router.push("/tasks");
    }
  }, [sessionData?.user, router]);

  return (
    <>
      <Head>
        <title>Todo list</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative z-10 mx-auto max-w-xl">
        {!sessionData ? <SignInCard /> : null}
      </div>
    </>
  );
};

export default Home;
