import SignInCard from "~/components/SignInCard";
import ThemeToggler from "~/components/ThemeToggler";
import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Todo list</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="h-[12.5rem] bg-mobile-header bg-cover  bg-no-repeat px-[1.625rem] sm:h-[18.75rem] sm:bg-desktop-header">
        <div className="mx-auto flex max-w-xl items-center justify-between pt-12">
          <h1 className="pt-1 text-3xl font-bold leading-[0px] tracking-[0.2em] text-white">
            TODO
          </h1>
          <ThemeToggler />
        </div>
      </header>
      <main className="relative z-10 mx-auto max-w-xl">
        <SignInCard />
      </main>
    </>
  );
};

export default Home;
