import SignInCard from "~/components/SignInCard";
import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();

  return (
    <>
      <Head>
        <title>Todo list</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="relative z-10 mx-auto max-w-xl">
        {sessionData?.user ? (
          <span>Logged in {sessionData.user.name}</span>
        ) : (
          <SignInCard />
        )}
      </div>
    </>
  );
};

export default Home;
